(use-modules (cellar model) (srfi srfi-1))
(define s (make-sheet 100 26))
(define (put! ref-name text) (set-cell-source! s (name->ref ref-name) text))
(define (shown ref-name) (cell-display s (name->ref ref-name)))
(define failures 0)
(define (check label expected actual)
  (if (equal? expected actual)
      (format #t "  ok   ~a~%" label)
      (begin (set! failures (+ failures 1))
             (format #t "  FAIL ~a: expected ~s got ~s~%" label expected actual))))

(format #t "-- references~%")
(check "A1" '(0 . 0) (name->ref "A1"))
(check "Z100" '(99 . 25) (name->ref "Z100"))
(check "roundtrip" "C7" (ref->name (name->ref "C7")))
(check "col AA" "AA" (column->name 26))
(check "bad ref" #f (name->ref "1A"))

(format #t "-- literals and arithmetic~%")
(put! "A1" "10")
(put! "A2" "32")
(put! "A3" "(+ A1 A2)")
(check "literal" "10" (shown "A1"))
(check "sum of refs" "42" (shown "A3"))

(format #t "-- recalculation~%")
(put! "A1" "100")
(check "recalc" "132" (shown "A3"))

(format #t "-- full Guile is available~%")
(put! "B1" "(string-upcase \"hello\")")
(put! "B2" "(apply + (map (lambda (n) (* n n)) (iota 5)))")
(put! "B3" "(if (> A3 100) 'big 'small)")
(check "string proc" "HELLO" (shown "B1"))
(check "higher order" "30" (shown "B2"))
(check "symbol" "big" (shown "B3"))

(format #t "-- helpers~%")
(put! "C1" "1") (put! "C2" "2") (put! "C3" "3")
(put! "C4" "(sum (range \"C1\" \"C3\"))")
(put! "C5" "(average (range \"C1\" \"C3\"))")
(put! "C6" "(cell \"C4\")")
(check "sum range" "6" (shown "C4"))
(check "average" "2" (shown "C5"))
(check "cell fn" "6" (shown "C6"))

(format #t "-- empty cells~%")
(put! "D1" "")
(check "empty shows blank" "" (shown "D1"))
(put! "D6" "(sum (range \"D1\" \"D5\"))")
(check "empty counts as 0" "0" (shown "D6"))
(put! "D2" "(sum (range \"D1\" \"D5\"))")
(check "range containing self is a cycle" "#ERR" (shown "D2"))

(format #t "-- errors~%")
(put! "E1" "(/ 1 0)")
(check "div by zero" "#ERR" (shown "E1"))
(check "is error" #t (cell-error? (cell-value s (name->ref "E1"))))
(put! "E2" "(+ 1")
(check "syntax error" "#ERR" (shown "E2"))
(put! "E3" "(undefined-proc 1)")
(check "unbound" "#ERR" (shown "E3"))

(format #t "-- circular references~%")
(put! "F1" "(+ F2 1)")
(put! "F2" "(+ F1 1)")
(check "cycle detected" "#ERR" (shown "F1"))
(format #t "       message: ~a~%" (cell-error-message (cell-value s (name->ref "F1"))))
(put! "G1" "(+ G1 1)")
(check "self reference" "#ERR" (shown "G1"))

(format #t "-- quoted data is not rebound~%")
(put! "H1" "'(A1 B1)")
(check "quote intact" "(A1 B1)" (shown "H1"))

(format #t "-- persistence~%")
(let ((saved (sheet->alist s))
      (s2 (make-sheet 100 26)))
  (alist->sheet! s2 saved)
  (check "roundtrip A3" "132" (cell-display s2 (name->ref "A3")))
  (check "roundtrip C4" "6" (cell-display s2 (name->ref "C4"))))

(format #t "~%~a~%" (if (zero? failures) "ALL TESTS PASSED" (format #f "~a FAILURE(S)" failures)))
(exit (if (zero? failures) 0 1))
