{-# LANGUAGE OverloadedStrings #-}

-- | S-expressions, as much of them as the wire needs.
--
-- Cellar's two halves talk in s-expressions, because the thing being talked
-- about is Scheme source text and there is no sense translating it into
-- something else on the way past.  This is the Haskell end of that: a reader
-- and a writer for the subset the protocol actually uses.
--
-- It is a subset on purpose, and the protocol is written to stay inside it:
-- symbols, strings, integers, booleans, lists and dotted pairs.  No characters,
-- no vectors, no quote sugar, no block comments, nothing that would make this
-- a Scheme reader rather than a wire format.  What the kernel sends is
-- generated by a program that knows the rules, so the job here is to read that
-- faithfully and to fail loudly on anything else rather than to be generous.
--
-- Lists are nested pairs ending in 'Nil', which is what they are in Scheme.
-- Doing it the other way -- a list constructor plus a special case for dotted
-- pairs -- makes the alists the kernel replies with into an awkward shape, and
-- alists are most of what comes back.
--
-- Reading and writing are in 'Text'; the strings and symbols inside a datum
-- are 'String'.  That is deliberate rather than half-done.  A message arrives
-- as bytes and leaves as bytes, and turning the whole of one into a linked
-- list of 'Char' merely to look at its parentheses is waste.  What comes /out/
-- of a datum is a cell's source or a sheet's name, and every caller of those
-- wants a 'String' and would only unpack it again.
module Cellar.Sexp
  ( Sexp (..)
  , list
  , toList
  , alist
  , lookupKey
  , parseSexp
  , writeSexp
  , asString
  , asInt
  , asSymbol
  , asBool
  ) where

import Data.Char (chr, isDigit, isSpace, ord)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import Data.Text.Lazy.Builder (Builder, fromString, fromText, singleton, toLazyText)
import Numeric (showHex)

data Sexp
  = Sym String
  | Str String
  | Num Integer
  | Real Double
  | Bool Bool
  | Nil
  | Pair Sexp Sexp
  deriving (Eq, Show)

-- | A proper list.
list :: [Sexp] -> Sexp
list = foldr Pair Nil

-- | The elements of a proper list, or 'Nothing' if it is dotted.
toList :: Sexp -> Maybe [Sexp]
toList Nil = Just []
toList (Pair a b) = (a :) <$> toList b
toList _ = Nothing

-- | An association list as key/value pairs.  Entries that are not pairs are
-- dropped rather than failing the whole message: the kernel may one day send a
-- key this version has never heard of, and ignoring it is how that stays
-- possible.
alist :: Sexp -> [(String, Sexp)]
alist s = case toList s of
  Nothing -> []
  Just entries -> [ (k, v) | Pair (Sym k) v <- entries ]

-- | Look a key up in an alist-shaped s-expression.
lookupKey :: String -> Sexp -> Maybe Sexp
lookupKey key = lookup key . alist

asString :: Sexp -> Maybe String
asString (Str s) = Just s
asString _ = Nothing

asInt :: Sexp -> Maybe Int
asInt (Num n) = Just (fromIntegral n)
asInt (Real d) = Just (truncate d)
asInt _ = Nothing

asSymbol :: Sexp -> Maybe String
asSymbol (Sym s) = Just s
asSymbol _ = Nothing

-- | Scheme's notion of truth, which is that everything except @#f@ is true.
asBool :: Sexp -> Bool
asBool (Bool b) = b
asBool _ = True

-- Reading

-- | Read one datum.  Returns what went wrong rather than throwing, because the
-- caller is a window and a malformed message is not a reason to take it down.
parseSexp :: Text -> Either String Sexp
parseSexp input = do
  (value, rest) <- datum (skip input)
  let leftover = skip rest
  if T.null leftover
    then Right value
    else Left ("trailing text after the datum: " ++ T.unpack (T.take 20 leftover))

-- | Whitespace and line comments.
skip :: Text -> Text
skip text = case T.uncons text of
  Just (c, rest)
    | isSpace c -> skip rest
    | c == ';' -> skip (T.drop 1 (T.dropWhile (/= '\n') rest))
  _ -> text

datum :: Text -> Either String (Sexp, Text)
datum text = case T.uncons text of
  Nothing -> Left "a message that stopped in the middle"
  Just ('(', rest) -> sequenceOf (skip rest)
  Just (')', _) -> Left "a close paren with nothing open"
  Just ('"', rest) -> stringLiteral rest []
  Just ('#', rest) -> case T.uncons rest of
    Just ('t', more) -> Right (Bool True, more)
    Just ('f', more) -> Right (Bool False, more)
    _ -> Left ("an unsupported # syntax: #" ++ T.unpack (T.take 8 rest))
  _ ->
    -- One slice for the whole token, rather than a character at a time.
    let (token, rest) = T.break delimiter text
    in if T.null token
         then Left ("an unreadable character: " ++ T.unpack (T.take 8 text))
         else Right (atom token, rest)

-- | Where a bare token stops.
delimiter :: Char -> Bool
delimiter c = isSpace c || c `elem` ("()\";" :: String)

atom :: Text -> Sexp
atom token
  | Just n <- readInteger token = Num n
  | Just d <- readDouble token = Real d
  | otherwise = Sym (T.unpack token)

readInteger :: Text -> Maybe Integer
readInteger token = case T.uncons token of
  Just ('-', rest)
    | not (T.null rest), T.all isDigit rest -> Just (negate (digits rest))
  Just _ | T.all isDigit token -> Just (digits token)
  _ -> Nothing

digits :: Text -> Integer
digits = T.foldl' (\acc c -> acc * 10 + fromIntegral (ord c - ord '0')) 0

readDouble :: Text -> Maybe Double
readDouble token = case reads (T.unpack token) :: [(Double, String)] of
  [(d, "")] -> Just d
  _ -> Nothing

-- | The rest of a list, having read the open paren.  A @.@ before the last
-- element makes it a dotted pair, which is how every alist the kernel sends is
-- shaped.
sequenceOf :: Text -> Either String (Sexp, Text)
sequenceOf text = case T.uncons text of
  Just (')', rest) -> Right (Nil, rest)
  Just ('.', rest) | maybe False (isSpace . fst) (T.uncons rest) -> do
    (tailValue, more) <- datum (skip rest)
    case T.uncons (skip more) of
      Just (')', final) -> Right (tailValue, final)
      _ -> Left "a dotted pair with more than one thing after the dot"
  _ -> do
    (this, rest) <- datum text
    (more, final) <- sequenceOf (skip rest)
    Right (Pair this more, final)

-- | A string literal, having read the open quote.  The escapes are the ones
-- Guile's writer emits.
--
-- The body is taken in runs rather than a character at a time: most strings
-- have no escapes in them at all, and one of those costs a single slice.
stringLiteral :: Text -> [Text] -> Either String (Sexp, Text)
stringLiteral text chunks =
  let (plain, rest) = T.break (\c -> c == '"' || c == '\\') text
      kept = plain : chunks
  in case T.uncons rest of
       Just ('"', more) -> Right (Str (T.unpack (T.concat (reverse kept))), more)
       Just ('\\', more) -> escaped more kept
       _ -> Left "a string that never ends"

escaped :: Text -> [Text] -> Either String (Sexp, Text)
escaped text chunks = case T.uncons text of
  Nothing -> Left "a string that ends in a backslash"
  Just (c, rest) -> case c of
    'n' -> stringLiteral rest ("\n" : chunks)
    't' -> stringLiteral rest ("\t" : chunks)
    'r' -> stringLiteral rest ("\r" : chunks)
    'a' -> stringLiteral rest ("\a" : chunks)
    'b' -> stringLiteral rest ("\b" : chunks)
    'f' -> stringLiteral rest ("\f" : chunks)
    'v' -> stringLiteral rest ("\v" : chunks)
    '0' -> stringLiteral rest ("\0" : chunks)
    '\\' -> stringLiteral rest ("\\" : chunks)
    '"' -> stringLiteral rest ("\"" : chunks)
    -- Guile writes an awkward character as \xHH; -- hex digits, then a
    -- semicolon.
    'x' ->
      let (hex, after) = T.break (== ';') rest
      in case T.uncons after of
           Just (';', more) | not (T.null hex), T.all isHexDigit hex ->
             stringLiteral more (T.singleton (chr (hexValue hex)) : chunks)
           _ -> Left "a \\x escape with no semicolon after it"
    -- A backslash before a newline is Guile's line continuation: both go.
    '\n' -> stringLiteral (T.dropWhile (\ch -> ch == ' ' || ch == '\t') rest) chunks
    other -> stringLiteral rest (T.singleton other : chunks)

isHexDigit :: Char -> Bool
isHexDigit c = isDigit c || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')

hexValue :: Text -> Int
hexValue = T.foldl' (\acc c -> acc * 16 + digitValue c) 0
  where
    digitValue c
      | isDigit c = ord c - ord '0'
      | c >= 'a' = ord c - ord 'a' + 10
      | otherwise = ord c - ord 'A' + 10

-- Writing

-- | Render a datum the way Guile's @read@ will take it back.
writeSexp :: Sexp -> Text
writeSexp = TL.toStrict . toLazyText . build

build :: Sexp -> Builder
build value = case value of
  Sym s -> fromString s
  Str s -> singleton '"' <> fromText (escape (T.pack s)) <> singleton '"'
  Num n -> fromString (show n)
  Real d -> fromString (show d)
  Bool True -> "#t"
  Bool False -> "#f"
  Nil -> "()"
  Pair a b -> singleton '(' <> build a <> rest b <> singleton ')'
  where
    -- A proper list prints as (a b c); an improper one as (a . b).
    rest Nil = mempty
    rest (Pair a b) = singleton ' ' <> build a <> rest b
    rest other = " . " <> build other

escape :: Text -> Text
escape = T.concatMap step
  where
    step c = case c of
      '"' -> "\\\""
      '\\' -> "\\\\"
      '\n' -> "\\n"
      '\t' -> "\\t"
      '\r' -> "\\r"
      _ | ord c < 0x20 -> T.pack ('\\' : 'x' : showHex (ord c) ";")
        | otherwise -> T.singleton c
