-- | S-expressions, as much of them as the wire needs.
--
-- Cellar's two halves talk in s-expressions, because the thing being talked
-- about is Scheme source text and there is no sense translating it into
-- something else on the way past.  This is the Haskell end of that: a reader
-- and a writer for the subset the protocol actually uses.
--
-- It is a subset on purpose, and the protocol is written to stay inside it:
-- symbols, strings, integers, booleans, lists and dotted pairs.  No characters,
-- no vectors, no quote sugar, no block comments, nothing that would make this
-- a Scheme reader rather than a wire format.  What the kernel sends is
-- generated by a program that knows the rules, so the job here is to read that
-- faithfully and to fail loudly on anything else rather than to be generous.
--
-- Lists are nested pairs ending in 'Nil', which is what they are in Scheme.
-- Doing it the other way -- a list constructor plus a special case for dotted
-- pairs -- makes the alists the kernel replies with into an awkward shape, and
-- alists are most of what comes back.
module Cellar.Sexp
  ( Sexp (..)
  , list
  , toList
  , alist
  , lookupKey
  , parseSexp
  , writeSexp
  , asString
  , asInt
  , asSymbol
  , asBool
  ) where

import Data.Char (chr, isDigit, isSpace, ord)
import Numeric (showHex)

data Sexp
  = Sym String
  | Str String
  | Num Integer
  | Real Double
  | Bool Bool
  | Nil
  | Pair Sexp Sexp
  deriving (Eq, Show)

-- | A proper list.
list :: [Sexp] -> Sexp
list = foldr Pair Nil

-- | The elements of a proper list, or 'Nothing' if it is dotted.
toList :: Sexp -> Maybe [Sexp]
toList Nil = Just []
toList (Pair a b) = (a :) <$> toList b
toList _ = Nothing

-- | An association list as key/value pairs.  Entries that are not pairs are
-- dropped rather than failing the whole message: the kernel may one day send a
-- key this version has never heard of, and ignoring it is how that stays
-- possible.
alist :: Sexp -> [(String, Sexp)]
alist s = case toList s of
  Nothing -> []
  Just entries -> [ (k, v) | Pair (Sym k) v <- entries ]

-- | Look a key up in an alist-shaped s-expression.
lookupKey :: String -> Sexp -> Maybe Sexp
lookupKey key = lookup key . alist

asString :: Sexp -> Maybe String
asString (Str s) = Just s
asString _ = Nothing

asInt :: Sexp -> Maybe Int
asInt (Num n) = Just (fromIntegral n)
asInt (Real d) = Just (truncate d)
asInt _ = Nothing

asSymbol :: Sexp -> Maybe String
asSymbol (Sym s) = Just s
asSymbol _ = Nothing

-- | Scheme's notion of truth, which is that everything except @#f@ is true.
asBool :: Sexp -> Bool
asBool (Bool b) = b
asBool _ = True

-- Reading

-- | Read one datum.  Returns what went wrong rather than throwing, because the
-- caller is a window and a malformed message is not a reason to take it down.
parseSexp :: String -> Either String Sexp
parseSexp input = do
  (value, rest) <- datum (skip input)
  case skip rest of
    "" -> Right value
    leftover -> Left ("trailing text after the datum: " ++ take 20 leftover)

-- | Whitespace and line comments.
skip :: String -> String
skip (c : cs) | isSpace c = skip cs
skip (';' : cs) = skip (drop 1 (dropWhile (/= '\n') cs))
skip s = s

datum :: String -> Either String (Sexp, String)
datum [] = Left "a message that stopped in the middle"
datum ('(' : cs) = sequenceOf (skip cs)
datum (')' : _) = Left "a close paren with nothing open"
datum ('"' : cs) = stringLiteral cs ""
datum ('#' : 't' : cs) = Right (Bool True, cs)
datum ('#' : 'f' : cs) = Right (Bool False, cs)
datum ('#' : cs) = Left ("an unsupported # syntax: #" ++ take 8 cs)
datum s =
  let (token, rest) = span (not . delimiter) s
  in if null token
       then Left ("an unreadable character: " ++ take 8 s)
       else Right (atom token, rest)

-- | Where a bare token stops.
delimiter :: Char -> Bool
delimiter c = isSpace c || c `elem` "()\";"

atom :: String -> Sexp
atom token
  | Just n <- readInteger token = Num n
  | Just d <- readDouble token = Real d
  | otherwise = Sym token

readInteger :: String -> Maybe Integer
readInteger ('-' : rest@(_ : _)) | all isDigit rest = Just (negate (digits rest))
readInteger s@(_ : _) | all isDigit s = Just (digits s)
readInteger _ = Nothing

digits :: String -> Integer
digits = foldl' (\acc c -> acc * 10 + fromIntegral (ord c - ord '0')) 0

readDouble :: String -> Maybe Double
readDouble s = case reads s :: [(Double, String)] of
  [(d, "")] -> Just d
  _ -> Nothing

-- | The rest of a list, having read the open paren.  A @.@ before the last
-- element makes it a dotted pair, which is how every alist the kernel sends is
-- shaped.
sequenceOf :: String -> Either String (Sexp, String)
sequenceOf (')' : cs) = Right (Nil, cs)
sequenceOf ('.' : c : cs)
  | isSpace c = do
      (tailValue, rest) <- datum (skip cs)
      case skip rest of
        (')' : more) -> Right (tailValue, more)
        _ -> Left "a dotted pair with more than one thing after the dot"
sequenceOf s = do
  (this, rest) <- datum s
  (more, final) <- sequenceOf (skip rest)
  Right (Pair this more, final)

-- | A string literal, having read the open quote.  The escapes are the ones
-- Guile's writer emits.
stringLiteral :: String -> String -> Either String (Sexp, String)
stringLiteral [] _ = Left "a string that never ends"
stringLiteral ('"' : cs) acc = Right (Str (reverse acc), cs)
stringLiteral ('\\' : c : cs) acc = case c of
  'n' -> stringLiteral cs ('\n' : acc)
  't' -> stringLiteral cs ('\t' : acc)
  'r' -> stringLiteral cs ('\r' : acc)
  'a' -> stringLiteral cs ('\a' : acc)
  'b' -> stringLiteral cs ('\b' : acc)
  'f' -> stringLiteral cs ('\f' : acc)
  'v' -> stringLiteral cs ('\v' : acc)
  '0' -> stringLiteral cs ('\0' : acc)
  '\\' -> stringLiteral cs ('\\' : acc)
  '"' -> stringLiteral cs ('"' : acc)
  -- Guile writes an awkward character as \xHH; -- hex digits, then a semicolon.
  'x' -> case break (== ';') cs of
    (hex, ';' : more)
      | not (null hex), all isHexDigit hex ->
          stringLiteral more (chr (hexValue hex) : acc)
    _ -> Left "a \\x escape with no semicolon after it"
  -- A backslash before a newline is Guile's line continuation: both go.
  '\n' -> stringLiteral (dropWhile (\ch -> ch == ' ' || ch == '\t') cs) acc
  other -> stringLiteral cs (other : acc)
stringLiteral (c : cs) acc = stringLiteral cs (c : acc)

isHexDigit :: Char -> Bool
isHexDigit c = isDigit c || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')

hexValue :: String -> Int
hexValue = foldl' (\acc c -> acc * 16 + digitValue c) 0
  where
    digitValue c
      | isDigit c = ord c - ord '0'
      | c >= 'a' = ord c - ord 'a' + 10
      | otherwise = ord c - ord 'A' + 10

-- Writing

-- | Render a datum the way Guile's @read@ will take it back.
writeSexp :: Sexp -> String
writeSexp value = go value ""
  where
    go (Sym s) = (s ++)
    go (Str s) = ('"' :) . escape s . ('"' :)
    go (Num n) = (show n ++)
    go (Real d) = (show d ++)
    go (Bool True) = ("#t" ++)
    go (Bool False) = ("#f" ++)
    go Nil = ("()" ++)
    go (Pair a b) = ('(' :) . go a . rest b . (')' :)

    -- A proper list prints as (a b c); an improper one as (a . b).
    rest Nil = id
    rest (Pair a b) = (' ' :) . go a . rest b
    rest other = (" . " ++) . go other

    escape s k = foldr step k s
    step c k = case c of
      '"' -> '\\' : '"' : k
      '\\' -> '\\' : '\\' : k
      '\n' -> '\\' : 'n' : k
      '\t' -> '\\' : 't' : k
      '\r' -> '\\' : 'r' : k
      _ | ord c < 0x20 -> '\\' : 'x' : showHex (ord c) (';' : k)
        | otherwise -> c : k
